/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DoanhThu.QuanLySuKien;
import DoanhThu.SuKienDinhKy;
import DoanhThu.SuKienHangThang;
import DoanhThu.SuKienMotLan;
import DoanhThu.SuKienTheoChuKy;
import IO.IO;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XPS
 */
public class SKDKView extends javax.swing.JFrame {

    /**
     * Creates new form SKDKView
     */
    QuanLySuKien qlsk;

    public SKDKView() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        qlsk = new QuanLySuKien();
//        System.out.println("1");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
//        System.out.println("1");
        for (int i = 0; i < qlsk.getDanhSachSuKienDinhKy().size(); i++) {
            SuKienDinhKy sk = qlsk.getDanhSachSuKienDinhKy().get(i);
//            System.out.println("1");
            if (sk instanceof SuKienHangThang) {
                System.out.println("1");
                SuKienHangThang skht = (SuKienHangThang) sk;
//                System.out.println("1");
                model.addRow(new Object[]{
                    skht.getTenSuKien(), skht.getNgayTiepTheo().format(DateTimeFormatter.ISO_DATE), skht.getLoaiSuKien(), "", skht.getNgay()
                });
            } else {
                SuKienTheoChuKy sktck = (SuKienTheoChuKy) sk;
                model.addRow(new Object[]{
                    sktck.getTenSuKien(), sktck.getNgayTiepTheo().format(DateTimeFormatter.ISO_DATE), sktck.getLoaiSuKien(), sktck.getSoNgayMotChuKy(), ""
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        themSK = new javax.swing.JButton();
        xoaSK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Trở về");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sự kiện", "Ngày tiếp theo", "Loại sự kiện", "Chu kỳ", "Ngày"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Danh sách các sự kiện định kỳ");

        themSK.setText("Thêm sự kiện");
        themSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSKActionPerformed(evt);
            }
        });

        xoaSK.setText("Xóa sự kiện");
        xoaSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaSKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(themSK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xoaSK)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themSK)
                    .addComponent(xoaSK))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSKActionPerformed
        // TODO add your handling code here:
        ThemSKDK themSKDK = new ThemSKDK();
        this.setVisible(false);
        themSKDK.setVisible(true);

    }//GEN-LAST:event_themSKActionPerformed

    private void xoaSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaSKActionPerformed
        // TODO add your handling code here:
        XoaSKDKView xoaskdkView = new XoaSKDKView();
        this.setVisible(false);
        xoaskdkView.setVisible(true);
    }//GEN-LAST:event_xoaSKActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        JFrame LichSuview = new LichSuView();
        this.setVisible(false);
        LichSuview.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JButton themSK;
    private javax.swing.JButton xoaSK;
    // End of variables declaration//GEN-END:variables
}
